### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Billiet-mc** [ianling/nespy#1]
Running test.py results in this error:

![image](https://user-images.githubusercontent.com/64997912/132528275-976cb14f-4093-4348-8e2f-1f67860481e5.png)

Implementing the code in the readme 
`
from nespy.nes import NES

nes = NES()
nes.load_rom("C:/roms/super-mario-bros.nes")
nes.run`

results in the same error.

**Comment by ianling** [comment]
Hello, as mentioned in the README, this project requires Python 3.9 or above in order to run it. It also isn't currently in state that will do anything when you run it, as only the CPU implementation is finished, so no graphics will be displayed. I recently picked the project up again after dropping it for a while, so maybe there will be some more progress soon.
